### ISSUE TITLE
Meross MSS425f / MSS426 extensions unavailable approx every 30-60 mins

### ISSUE THREAD

**Issue by retro-kid** [krahabb/meross_lan#105] opened 2021-10-25 12:20 UTC
Hello

Firstly - a big thank you for this integration. Really appreciate the work you are doing..

Been running multiple MSS310 smart sockets for a while now - no issues what so ever.

At weekend i purchased x2 Meross Surge Protected Smart Extensions (MSS425f - 4 gang and MSS426 - 6 gang) to place into a new feature wall i am building:

MSS425 is on Hardware Version 4.0 and Firmware Version 4.2.3
MSS426 is on Hardware Version 6.0 and Firmware Version 6.1.4

I had to follow the trick in #83 to get the devices added to Home Assistant - and both now have the device key from Meross Cloud (they both have the same device key?). Once this was added, i could control the individual smart sockets on the extension bars via Home Assistant - Awesome!

What i'm finding however, is approx every 30 -60 mins, they go "offline" in HA (but still controllable on Meross app during this period). After around 30 seconds they come back online via HA and can be controlled again. During this offline period all the entities state "Unavailable". Can tell this is happening also as the last changed date of the entity refers to the time they last came online. At the moment for sockets i know haven't changed - MSS310 - 14hrs (last reboot of HA), MSS425 - 31mins, MSS426 - 30mins

Looking at logs i see this for the two devices repeatedly when they go offline:

MerossDevice(<serial for MSS425>) error in async_http_request: local variable 'response' referenced before assignment
MerossDevice(<serial for MSS426>) error in async_http_request: local variable 'response' referenced before assignment
MerossDevice(<serial for MSS425>) error in async_http_request: Server disconnected
MerossDevice(<serial for MSS426>) error in async_http_request: Server disconnected

When they are online, they function perfectly may i add :-)

Both within range of good Wi-Fi on a separate 2.4 Ghz SSID reserved for smart devices only - 97% signal strength on Unifi. Both have device key in their config (albeit the same key for both). Both are up to date firmware wise (probably a bad thing but that's how they came). Home Assistant wise, i'm running 2021.10.6 and running the latest version of the Meross_LAN integration via HACS.

Any ideas?
Best Regaeds.

**Comment by krahabb** [comment] 2021-11-01 16:31
Hello @retro-kid,
I'm 'back to work' trying to check if everything is ok with the upcoming november core release and I want to dig a bit into these 'Server disconnected' which are likely due to a wrong message issued to the devices (putting them a bit offline when this happens)
I would really need the previously mentioned 'traces' in order to try understand where things get bad so, if you're still up, you could enable tracing (per device) in the device configuration entry in HA (from the Integrations UI).
Enabling the 'trace' checkbos will start recording every eXchanged message between meross_lan and the device and this should last about 10 minutes. If it happens the device is going offline while 'tracing' it that would be awesome but, nevertheless, don't get too mad trying to 'align stars' on that. Some clues could come even if the 'Server disconnected' error doesn't happen.
Of course, if you know how to reliably reproduce or predict the disconnection that would be super perfect!

After collecting the traces (they'll be under custom_components/meross_lan/traces) please post them here (or so :)

Thank you.

**Comment by codepoet4** [comment] 2021-11-05 16:26
Hi @krahabb - I am having the same issue, and have some time to collect these traces - however, I don't see the 'enable tracing' checkbox (I see Device Info/Controls/Automations/Scenes/etc... - perhaps I'm looking in the wrong place?)..  I'm seeing this on MSS110's, perhaps tracing is not available on these?
![Capture](https://user-images.githubusercontent.com/15722515/140544369-cf89294e-1fb3-448a-8621-eaea8a619882.JPG)
.

**Comment by krahabb** [comment] 2021-11-06 12:38
Hello @codepoet4,
the 'tracing' feature is enabled from the `Integrations` configuration panel for the device

**Comment by codepoet4** [comment] 2021-11-06 15:35
Here is a capture with a disconnect at 9:09:29, and another at 9:18:00 - they also always seem to go offline right after I start the trace...  

[mss110-1636211900.csv](https://github.com/krahabb/meross_lan/files/7490737/mss110-1636211900.csv)

**Comment by krahabb** [comment] 2021-11-06 17:27
Hello @codepoet4,
The first disconnection (at 9:08:20) you experience while tracing is because of a 'spurious' inquiry which the device doesn't like at all (meross_lan when tracing tries to query all of the available 'endpoints' exposed by the device). 
When tracing I usually exclude those 'endpoints' when their behaviour is known to cause a disconnect but, your device is exposing a kind of new endpoint which I'm not filtering out: this is already being fixed with the next release so it's not an issue actually, especially since while not tracing, meross_lan is not sending the 'offending' query.

The other two are instead likely the same you experience during normal operations.

I suspect this is a 'side effect' of an incorrect key configuration for the device. If the device is still paired to Meross cloud service it has a secret key used to sign message exchange. If you leave the key configuration field empty in meross_lan, my code tries to hack the protocol and it usually works but sometimes not and I suspect the newer firmwares are closing a bit on this kind of hack so it turns out it works less than it used to.

If you left the key configuration field empty in meross_lan your option is to retrieve the original secret key by using a feature only available in meros_lan when adding the device for the first time, so you have to drop the current integration configuration and re-add it again.

Since the actual implementation is a bit 'inconsistent' during configuration I suggest you to follow the comments in this thread/post https://github.com/krahabb/meross_lan/issues/92#issuecomment-929545495

**Comment by codepoet4** [comment] 2021-11-06 21:38
Hmm.  I did have a value in that field (your integration put one in there..). The first plug I configured, I was asked for my meross username/password, and since then it fill in that field for me.  ![image](https://user-images.githubusercontent.com/15722515/140624555-54fe8ac8-6b89-4597-8be1-5b4b82c0f73b.png)

**Comment by krahabb** [comment] 2021-11-07 09:48
Well, it looks like my 'guess' was wrong about the key.

At the moment I can't really figure out why the device disconnects so randomly. I experience sometimes the same behaviour even if in my xperience it doesn't happen so often.

Anyway, since the device just 'fails' once and then keeps working on subsequent calls, I'm refining meross_lan to be more 'easy' on these kind of disconnects and do not report the device as offline when it just happens once.
I'm still testing a bit on the consequences since all the timeouts and offline behaviours are likely to add up to the 'mess' but  the next release should 'fix' this kind of errors

**Comment by codepoet4** [comment] 2021-12-02 16:57
Just a note on this - I applied the Rush release yesterday, and have not had one single 'unavailable' since.  I thought you might like to know.  Thanks!

**Closed** 2022-01-11 09:49 UTC
Labels: fixed
