### ISSUE TITLE
Blocking call to import_module inside event loop in meross_lan

### ISSUE THREAD

**Issue by MDsza** [krahabb/meross_lan#436] opened 2024-05-16 20:52 UTC
I am receiving the following warning in my Home Assistant logs:

Logger: homeassistant.util.loop
Source: util/loop.py:99
First occurred: 21:23:47 (6 occurrences)
Last logged: 21:23:47

Detected blocking call to import_module inside the event loop by custom integration 'meross_lan' at custom_components/meross_lan/meross_device.py, line 472: module = import_module( (offender: /config/custom_components/meross_lan/meross_device.py, line 472: module = import_module(), please create a bug report at https://github.com/krahabb/meross_lan/issues

Steps to reproduce:

	1.	Install meross_lan integration
	2.	Observe the logs for the above warning

System information:

	•	Core 2024.5.3 / Supervisor 2024.05.1 / Operating System 12.3 / Frontend 20240501.1
	•	meross_lan version: 5.0.4
	•	Installation type: Home Assistant OS
	•	Hardware: ZimaBoard 832 - Proxmox Cluster 

Could you please investigate this issue? Thank you!

**Comment by krahabb** [comment] 2024-05-16 21:04
Hello,
there's an already opened issue about this
Duplicate of #427

**Comment by krahabb** [comment] 2024-05-16 21:05
Duplicate of #427

**Closed by krahabb** 2024-05-16 21:05 UTC
