### ISSUE TITLE
Can't Change IPv4 Address when it is already registered

### ISSUE THREAD

**Issue by xvolte** [krahabb/meross_lan#128] opened 2021-12-07 23:27 UTC
## Version of the custom_component
meross lan v2.4.2

## Configuration
no yaml conf, that is the problem, all was done by the interface "integration"

## Describe the bug
I set up all my meross devices couple of months ago, and it worked very well. Thanks for your work.
However, i started segmenting my Lan with VLANS and now i have other ip addresses assigned to the devices.
If there was a way to change manually the ip address that would be awesome, because this way i would not need to change my lovelace card nor my nodered automation, which are all based on the devices entity id.

Can you tell me how to proceed? might be good if there was an option to be able to change the ip of a device once it is configured.

## Debug log

It is not a bug, but it is an issue. One could consider this a feature request maybe ? it depends if there is a solution to this already or not

**Comment by krahabb** [comment] 2021-12-08 13:54
Hello @xvolte ,
Yeah this is something I often think of: the ability to change the ip address for an already known device. Up to this point I've always considered an ip change as a device change so I've never considered the ip as an editable property but as an identifier property. You're right anyway there could be some cases where would be benficial to not re.configure the integration from scratch if a device jsut moves to a different ip. 
Beside this 'theoretical' consideration I'm scared that allowing editing the ip would need some added logic in meross_lan to check the address change is still related to the same device (identified by its own UUID that is) and so I've always postponed the implementation which itself would be easy in terms of added UI fields.

Thinking of it right now..if not too cumbersome I'd post a patch with some other bug fixing very soon

**Comment by unlucio** [comment] 2021-12-20 22:16
I suspect I am too "victim" of this issue as I recently revamped my plan and put order in my DHCP changing pretty much all the devices' IP in my network.
Now I'm in this weird situation where the integration seems working fine:
<img width="268" alt="Screenshot 2021-12-20 at 23 09 01" src="https://user-images.githubusercontent.com/778799/146839468-75bbabfb-939b-4005-95a9-12e9c424b5b4.png">
While all the devices and entities  are un unavailable
<img width="1336" alt="Screenshot 2021-12-20 at 23 09 27" src="https://user-images.githubusercontent.com/778799/146839620-501986b0-33f5-4170-96ac-9b9e93f3ea95.png">
and since one of these plugs controls the booster heater in my bathroom I woke up and had to take a shower in 18ºC 🥶

Jokes aside my 1st thought was to remove the integration and add it again, promoting the rediscovery of the devices.
The problem is: there is no remove/delete button and even if I fiscally remove the module from HA (from hacs), as soon as the module is reinstalled I'm back on square one (and frozen butt in the morning).

Please adivese?

**Comment by krahabb** [comment] 2021-12-22 16:14
Hello @unlucio ,
I'm sorry for the 'cold' showers ;) and slowly working toward allowing the ip address edit in configuration.
At the moment, deleting the meross_lan folder does not remove the configuration from HA so it is nearly useless.
You can instead remove and readd every single 'integration' entry : not the devices nor the entities.
Just enter a single card (every physical device has 1 integration configuration entry) from the integrations page and, by using the 'dots' menu on the panel hit 'Delete' in order to cleanup the HA configuration from any 'awareness' of the device.
Then you'll be able to either manually add a new intgration configuration for the removed device or wait until discovery does its job (which could never happen at least until you restart HA)

**Comment by roberttco** [comment] 2021-12-29 23:32
Unfortunately deleting the device to remove awareness of it doesn't seem to completely work.  I'm looking forward to the fix for this issue...

**Comment by krahabb** [comment] 2022-02-15 10:57
The incoming release allows updating the host address in configuration (allowed the device is really the same..else: boom!)

**Closed by krahabb** 2022-02-15 10:57 UTC
Labels: enhancement
