### ISSUE TITLE
Validation of translation placeholders for localized (it) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed

### ISSUE THREAD

**Issue by micium** [krahabb/meross_lan#411] opened 2024-03-16 15:50 UTC
Registratore: homeassistant.helpers.translation
Fonte: helpers/translation.py:345
Prima occorrenza: 15:23:48 (1 occorrenze)
Ultima registrazione: 15:23:48

Validation of translation placeholders for localized (it) string component.meross_lan.issues.cloud_token_expired.fix_flow.step.profile.description failed

-->

## Version of the custom_component
v5.0.2
If you are unsure about the version check the const.py file.
-->

## Configuration

Add your logs here.

```

## Describe the bug
message in the log from HA 2024.3.0

**Comment by krahabb** [comment] 2024-03-16 20:25
Looks like a duplicate of #400. At any rate it falls in the same category and I'm awaiting to understand what's going on with HA core since this was likely due to a recent change committed to the core which has no great documentation

**Comment by krahabb** [comment] 2024-03-18 20:47
It's effectively a bug in translations file...couldn't reproduce it until I've switched to the italian translations..

**Comment by micium** [comment] 2024-03-18 21:36
I updated the meross_lan integration to 5.0.3 version  and I can confirm the issue is resolved.

Thanks a lot

**Closed** 2024-03-19 05:23 UTC
Labels: bug, fixed
