### ISSUE TITLE
When trying to switch on a meross lightbulb an error occurs

### ISSUE THREAD

**Issue by vibora** [krahabb/meross_lan#309] opened 2023-08-04 02:41 UTC
## Version of the custom_component

4.3.0

Add your logs here.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/meross_lan/light.py:57 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 04:04:17 (3 occurrences) 
Last logged: 04:18:34

[547607470272] unsupported operand type(s) for <<: 'float' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 62, in service_func_proxy
    await existing_service.job.target(call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/meross_lan/light.py", line 234, in async_turn_on
    light[mc.KEY_RGB] = _rgb_to_int(rgb)
                        ^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/light.py", line 57, in _rgb_to_int
    return (red << 16) + (green << 8) + blue
                          ~~~~~~^^~~
TypeError: unsupported operand type(s) for <<: 'float' and 'int'

## Describe the bug
Always when I try to switch the lightbulb the error message appears and device is not switched.

## Debug log

2023-08-04 04:37:05.094 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547782799552] unsupported operand type(s) for <<: 'float' and 'int'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/adaptive_lighting/hass_utils.py", line 62, in service_func_proxy
await existing_service.job.target(call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
response_data = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
await light.async_turn_on(**filter_turn_on_params(light, params))
File "/config/custom_components/meross_lan/light.py", line 234, in async_turn_on
light[mc.KEY_RGB] = _rgb_to_int(rgb)
^^^^^^^^^^^^^^^^
File "/config/custom_components/meross_lan/light.py", line 57, in _rgb_to_int
return (red << 16) + (green << 8) + blue
~~~~~~^^~~
TypeError: unsupported operand type(s) for <<: 'float' and 'int'

**Comment by krahabb** [comment] 2023-08-04 14:12
Hello @vibora,
I guess you're on HA 2023.8 experiencing this issue...
I'd need the device type and also the kind of setting for the light bulb i.e. if it's set on temperature mode or rgb mode (it looks like the issue appears when managing the RGB components of the command and by the look of it, this is likely an HA2023.8 bug). 
Nevertheless, I'll keep testing and looking for possible solutions to this.

**Comment by vibora** [comment] 2023-08-04 18:09
Exactly, it‘s 2023.8.
The device is Raspi 3.+.
It is set to RGB mode.
Thank you very much for testing it further.
It appeared straight after the HA update.

**Comment by krahabb** [comment] 2023-08-04 18:55
I've tested meross_lan 4.3.0 on HA 2023.8.0 and it looks like my msl120 (smart rgb bulb) works (switching on/off, setting rgb color, setting color temperature) without any glitch.

Looking at the exception log, I see you are using `adaptive_lightining` integration and that is probably the cause of the issue:
I've searched through the code of that piece of software and it looks like it is using floating numbers where HA expects integers (namely, the R-G-B components of the light.turn_on command)
To be honest, I can't see a reason why it was working before (if it worked) since that custom component/integration looks wrong in how it implements its behavior. This is at least my impression at first sight: I would need to deeply inspect that code to better understand what it does, but maybe you could try raise an issue with the developer/repository of that custom component

**Comment by krahabb** [comment] 2023-10-20 13:42
@vibora , @Chris112,
were you able to resolve the issue ? I'm closing this for the moment since I'm still strongly convinced this is an `adaptive_lighting` bug

**Comment by Chris112** [comment] 2023-10-20 14:08
> @vibora , @Chris112, were you able to resolve the issue ? I'm closing this for the moment since I'm still strongly convinced this is an `adaptive_lighting` bug

Hey, the issue still currently exists.

I've got 2 identical Meross lamps, one added via meross_lan and the other via homekit device and the homekit one is working as expected with the same adaptive lighting config.

Using the adaptive lighting service instead of light.turn_on is my current workaround:

``` yaml
service: adaptive_lighting.apply
data:
  entity_id: switch.ambient_adaptive_lighting
  lights:
    - light.bedroom_lamp
  adapt_brightness: true
  adapt_color: true
  prefer_rgb_color: true
  turn_on_lights: true
```

Error log when attempting to use light.turn_on:

``` text
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:51:42 PM (1 occurrences)
Last logged: 9:51:42 PM

[140211628494400] Invalid value for RGB!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 62, in service_func_proxy
    await existing_service.job.target(call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/meross_lan/light.py", line 234, in async_turn_on
    light[mc.KEY_RGB] = _rgb_to_int(rgb)
                        ^^^^^^^^^^^^^^^^
  File "/config/custom_components/meross_lan/light.py", line 56, in _rgb_to_int
    raise ValueError("Invalid value for RGB!")
ValueError: Invalid value for RGB!
```

**Comment by krahabb** [comment] 2023-10-21 06:17
I think I've detected the issue.
If I'm not wrong, `adaptive_lighting` adapts the color temperature and then converts it to an RGB value when `prefer_rgb_color: true`. Since the Meross device should support color temperature too (at least most of them, not sure yours) you could try removing the `prefer_rgb_color: true` setting and see if, in color temperature mode, the light works fine.

In details:
When `adaptive_lighting` (force) convert a color temperature to an RGB value it uses an 'official' HA function that returns a set of RGB values as floats instead of integers and uses those directly (thus crashing meross_lan that expects int(s) as per official HA docs)

I still think the bug is in `adaptive_lighting` but for the sake of 'robustness' I'm going to fix meross_lan code in order to accept this.

I'll post the fix very soon (current `Cloudy.4.alpha.0` pre-release doesn't fix this yet) but in the meantime, if your Meross supports color temp and you could try remove the `prefer_rgb_color: true` setting and confirm it works, that would be a great help, stating the incoming fix will suffice

**Comment by vibora** [comment] 2023-10-21 18:23
I switched long time ago to the direct homekit integration to solve the issue.
But I reverted for a short while and can confirm that the removal of `prefer_rgb_color: true` helps.
Best regards and thank you for the fix!

**Comment by krahabb** [comment] 2023-12-16 09:45
Likely definitevely fixed in Cloudy.4

**Closed by krahabb** 2023-12-16 09:45 UTC
Labels: bug, fixed
