### ISSUE TITLE
msg100 state won't update, warnings in log

### ISSUE THREAD

**Issue by dergreg** [krahabb/meross_lan#462] opened 2024-06-20 22:06 UTC
## Version of the custom_component

5.2.0

## Configuration

HA 2024.6.3

What kind of configuration yaml is expected here? The device is configured using the Meross MQTT via the device key, the connection mode is set to "auto".

## Describe the bug

Since about 1 or 2 weeks the state of my garage door (msg100) is not reported correctly anymore in HA (but it's fine in the Meross app).

When I open the garage door using the HA cover entity, it will be shown as "open". But when I close it using my physical garage door button, the entity stays "open" forever.

Here I open the garage door using HA:

```
2024-06-20 18:17:28.533 DEBUG (MainThread) [custom_components.meross_lan.profile_@0] MerossMQTTConnection(###################0:@0): RX(mqtt) PUSH Appliance.GarageDoor.State (uuid:###############################0 messageId:d1e8282c79073219f240f4ed2a750251)
2024-06-20 18:17:28.533 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(mqtt) PUSH Appliance.GarageDoor.State (messageId:d1e8282c79073219f240f4ed2a750251)
2024-06-20 18:17:28.533 WARNING (MainThread) [custom_components.meross_lan.msg100_###############################0] AttributeError('list' object has no attribute 'get') in NamespaceHandler(Appliance.GarageDoor.State)._handle_dict: payload={'state': [{'open': 1, 'lmTime': 1718900248, 'channel': 0}]}
```

At 18:20:44 I have closed the garage door using the physical button:

```
2024-06-20 18:20:44.979 DEBUG (MainThread) [custom_components.meross_lan.profile_@0] MerossMQTTConnection(###################0:@0): RX(mqtt) PUSH Appliance.GarageDoor.State (uuid:###############################0 messageId:d4bfac98c86708578d4c72b98cd24bfa)
2024-06-20 18:20:44.979 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(mqtt) PUSH Appliance.GarageDoor.State (messageId:d4bfac98c86708578d4c72b98cd24bfa)
2024-06-20 18:20:44.979 WARNING (MainThread) [custom_components.meross_lan.msg100_###############################0] AttributeError('list' object has no attribute 'get') in NamespaceHandler(Appliance.GarageDoor.State)._handle_dict: payload={'state': [{'channel': 0, 'open': 0, 'lmTime': 1718900444}]}
```

## Debug log

```
2024-06-20 18:17:28.533 DEBUG (MainThread) [custom_components.meross_lan.profile_@0] MerossMQTTConnection(###################0:@0): RX(mqtt) PUSH Appliance.GarageDoor.State (uuid:###############################0 messageId:d1e8282c79073219f240f4ed2a750251)
2024-06-20 18:17:28.533 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(mqtt) PUSH Appliance.GarageDoor.State (messageId:d1e8282c79073219f240f4ed2a750251)
2024-06-20 18:17:28.533 WARNING (MainThread) [custom_components.meross_lan.msg100_###############################0] AttributeError('list' object has no attribute 'get') in NamespaceHandler(Appliance.GarageDoor.State)._handle_dict: payload={'state': [{'open': 1, 'lmTime': 1718900248, 'channel': 0}]}
2024-06-20 18:17:45.382 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.GarageDoor.State (messageId:2b093516cd984028bea656642c899be8)
2024-06-20 18:17:45.396 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.GarageDoor.State (messageId:2b093516cd984028bea656642c899be8)
2024-06-20 18:17:57.664 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:17:57.665 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:4e5f670ef62945d5bbae106baaa55faf)
2024-06-20 18:17:57.685 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:4e5f670ef62945d5bbae106baaa55faf)
2024-06-20 18:17:57.685 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:17:57.685 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:18:27.687 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:18:27.687 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:ec626d8167d341479465a3e603583535)
2024-06-20 18:18:27.708 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:ec626d8167d341479465a3e603583535)
2024-06-20 18:18:27.708 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:18:27.708 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:18:57.709 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:18:57.710 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:b91cbc8abb6545a399bd8086c7c3dc31)
2024-06-20 18:18:57.731 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:b91cbc8abb6545a399bd8086c7c3dc31)
2024-06-20 18:18:57.731 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:18:57.731 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:19:27.732 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:19:27.733 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:cbb215aefdcd44c9985e730da9bb8807)
2024-06-20 18:19:27.754 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:cbb215aefdcd44c9985e730da9bb8807)
2024-06-20 18:19:27.754 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:19:27.754 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:19:57.756 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:19:57.757 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:a55d216382d046ab85c5d2e9edb30013)
2024-06-20 18:19:57.778 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:a55d216382d046ab85c5d2e9edb30013)
2024-06-20 18:19:57.778 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:19:57.778 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:20:27.780 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 18:20:27.780 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:e0c1e1c321624ee2b10f6243ed702419)
2024-06-20 18:20:27.800 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:e0c1e1c321624ee2b10f6243ed702419)
2024-06-20 18:20:27.800 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 18:20:27.801 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 18:20:44.979 DEBUG (MainThread) [custom_components.meross_lan.profile_@0] MerossMQTTConnection(###################0:@0): RX(mqtt) PUSH Appliance.GarageDoor.State (uuid:###############################0 messageId:d4bfac98c86708578d4c72b98cd24bfa)
2024-06-20 18:20:44.979 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(mqtt) PUSH Appliance.GarageDoor.State (messageId:d4bfac98c86708578d4c72b98cd24bfa)
2024-06-20 18:20:44.979 WARNING (MainThread) [custom_components.meross_lan.msg100_###############################0] AttributeError('list' object has no attribute 'get') in NamespaceHandler(Appliance.GarageDoor.State)._handle_dict: payload={'state': [{'channel': 0, 'open': 0, 'lmTime': 1718900444}]}
```

Some logs directly after integration restart:

```
2024-06-20 23:11:27.749 DEBUG (MainThread) [custom_components.meross_lan] async_setup_entry (entry_id:e32d58cf89d7a808dac47df33cd6cc9b)
2024-06-20 23:11:27.750 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] ProtocolSensor(sensor_protocol): init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarage(0): init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarageTimeoutBinarySensor(0_problem): init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLDNDLightEntity(dnd): init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLSignalStrengthSensor(signal_strength): init
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: update }
2024-06-20 23:11:27.751 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: sensor }
2024-06-20 23:11:27.752 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: switch }
2024-06-20 23:11:27.752 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: number }
2024-06-20 23:11:27.752 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: cover }
2024-06-20 23:11:27.752 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: binary_sensor }
2024-06-20 23:11:27.752 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] platform_setup_entry { platform: light }
2024-06-20 23:11:27.757 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] linked to profile:@0
2024-06-20 23:11:27.757 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] mqtt_attached to ###################0:@0
2024-06-20 23:11:27.757 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] mqtt_connected to ###################0:@0
2024-06-20 23:11:27.759 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:11:27.759 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.System.All (messageId:720874837312478fb4382e5937a47e62)
2024-06-20 23:11:27.783 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.System.All (messageId:720874837312478fb4382e5937a47e62)
2024-06-20 23:11:27.783 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Switching protocol to http
2024-06-20 23:11:27.784 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Back online!
2024-06-20 23:11:27.784 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.System.Debug (messageId:24b5c3b232a441288494e70d20fe004b)
2024-06-20 23:11:27.785 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:6e6d937e25cc4179818b6442b08748f4)
2024-06-20 23:11:27.803 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.System.Debug (messageId:24b5c3b232a441288494e70d20fe004b)
2024-06-20 23:11:27.826 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:6e6d937e25cc4179818b6442b08748f4)
2024-06-20 23:11:27.826 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:11:27.826 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarageConfigNumber(config_signalDuration): init
2024-06-20 23:11:27.827 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarageConfigSwitch(config_buzzerEnable): init
2024-06-20 23:11:27.827 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarageConfigNumber(config_doorOpenDuration): init
2024-06-20 23:11:27.827 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] MLGarageConfigNumber(config_doorCloseDuration): init
2024-06-20 23:11:27.827 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Diagnostic scan begin
2024-06-20 23:11:27.828 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.Config.Info (messageId:e9f53a7f2f87445dbb86e4ba1b6da7e4)
2024-06-20 23:11:27.843 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.Config.Info (messageId:e9f53a7f2f87445dbb86e4ba1b6da7e4)
2024-06-20 23:11:27.843 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.System.Debug (messageId:bfde171f82cc49e88b320b45c93f8a46)
2024-06-20 23:11:27.866 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.System.Debug (messageId:bfde171f82cc49e88b320b45c93f8a46)
2024-06-20 23:11:27.866 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.Control.ToggleX (messageId:59d2ad64351c4c1588761464dd18e4f6)
2024-06-20 23:11:27.880 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.Control.ToggleX (messageId:59d2ad64351c4c1588761464dd18e4f6)
2024-06-20 23:11:27.880 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) GET Appliance.GarageDoor.State (messageId:86b518e43433407898159cedefca2a3c)
2024-06-20 23:11:27.895 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) GETACK Appliance.GarageDoor.State (messageId:86b518e43433407898159cedefca2a3c)
2024-06-20 23:11:27.895 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Diagnostic scan end
2024-06-20 23:11:27.895 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 23:11:57.896 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:11:57.897 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:900fa14a0cae40d8b495db27fcc163ff)
2024-06-20 23:11:57.919 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:900fa14a0cae40d8b495db27fcc163ff)
2024-06-20 23:11:57.919 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:11:57.919 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 23:12:27.920 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:12:27.921 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:82705623f03f4c93b601838c4bc9a0b9)
2024-06-20 23:12:27.946 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:82705623f03f4c93b601838c4bc9a0b9)
2024-06-20 23:12:27.946 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:12:27.946 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 23:12:57.948 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:12:57.948 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:922935b559764249b279821639404480)
2024-06-20 23:12:57.969 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:922935b559764249b279821639404480)
2024-06-20 23:12:57.969 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:12:57.970 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 23:13:27.970 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:13:27.971 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:1e1408e1d1e04b5fbd3925c169cf966e)
2024-06-20 23:13:27.990 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:1e1408e1d1e04b5fbd3925c169cf966e)
2024-06-20 23:13:27.991 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:13:27.991 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
2024-06-20 23:13:57.992 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling begin
2024-06-20 23:13:57.993 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] TX(http) SET Appliance.Control.Multiple (messageId:bf448446f7be4d48b4d126c90a7bb845)
2024-06-20 23:13:58.016 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] RX(http) SETACK Appliance.Control.Multiple (messageId:bf448446f7be4d48b4d126c90a7bb845)
2024-06-20 23:13:58.016 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Appliance.Control.Multiple requests=3 (responses=3) expected size=1360 (actual=1332)
2024-06-20 23:13:58.016 DEBUG (MainThread) [custom_components.meross_lan.msg100_###############################0] Polling end
```

**Comment by krahabb** [comment] 2024-06-21 18:17
This was likely fixed in 5.2.2 ..if not.."Houston we have  a problem"

**Comment by krahabb** [comment] 2024-06-21 19:11
duplicate of #439

**Comment by dergreg** [comment] 2024-06-22 07:57
Yes, 5.2.2 did fix it. Many thanks!

**Closed** 2024-06-22 07:57 UTC
