### ISSUE TITLE
Support MSS315 (Smart Wi-Fi Pług Mini with matter)

### ISSUE THREAD

**Issue by vordenken** [krahabb/meross_lan#312] opened 2023-09-01 11:50 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use the new smart plug totally local - specifically the power meter feature. 
I can enable/disable the plug already with your plugin but not use the pwoermeter features - the HA UI just shows zeros.

**Describe the solution you'd like**
Add the feature to locally get the power meter data.

**Comment by krahabb** [comment] 2023-09-08 08:57
Hello @vordenken !
in order to understand if it's possible I would need a [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) to inspect the device exposed features and try to use that

**Comment by vordenken** [comment] 2023-09-08 10:40
[config_entry-meross_lan-1f0b10ed617647b67d0c29cf442699c6.json-2.txt](https://github.com/krahabb/meross_lan/files/12558552/config_entry-meross_lan-1f0b10ed617647b67d0c29cf442699c6.json-2.txt)

I hope this is the right log :)

**Comment by jjleto** [comment] 2023-09-09 06:31
on Home Assistant 2023.9.1 if mss315 is set to matter is lost in meross lan (This entity is no longer provided by the meross_lan integration. If the entity is no longer in use, delete it in the settings.) vice versa if set on meross lan is lost on matter
[home-assistant_2023-09-09T06-31-10.011Z.log](https://github.com/krahabb/meross_lan/files/12565091/home-assistant_2023-09-09T06-31-10.011Z.log)

**Comment by vordenken** [comment] 2023-10-27 20:01
hey @krahabb,
just checking if there is an update on this topic :)

**Comment by krahabb** [comment] 2023-10-28 18:08
Hello @vordenken,
This got 'lost in the threads', sorry for this happening.
It appears by your log the issue is the same as other mssXXX (#318) since `meross_lan` is actually querying the device sensors but it keeps reporting '0' (so you should have the sensors available in HA UI, except their values are '0' as actually reported by the device). I can't honestly figure out (still) what's wrong with some mssXXX showing this behavior since it is recurring here and there over time..maybe some firmwares are particularly glitched or, in my hypothesis, the device shows this behavior when there's something wrong with the time settings.
Either it is unable to contact an NTP time service in order to correctly measure energy and the likes over time (but your trace shows the device time is correct nevertheless).
Or, my other guess, the issues lies in the incorrect timezone setting for the device. I see your doesn't have a timezone configured so it doesn't know the UTC offsets and/or daylight saving time changes and this might induce this kind of bug.
Many times in fact, the device just starts measuring again after a reboot...
For the time being you could just try and set the correct device timezone with the app (since your devices are still Meross binded and `meross_lan` doesn't touch any time or timezone configuration when the device is Meross-binded)

**Comment by krahabb** [comment] 2023-10-29 08:21
Duplicate of #300

**Closed by krahabb** 2023-10-29 08:21 UTC
