### ISSUE TITLE
Once timezone is set it cannot be cleared + antiquated pytz

### ISSUE THREAD

**Issue by jaytea33** [krahabb/meross_lan#84] opened 2021-09-20 00:52 UTC
It seems that once the timezone setting is set in the Web UI that it can't be cleared in the actual config itself. If you block the (MSG100) device from WAN entirely, this causes it to spam NTP requests repeatedly via outbound UDP port 123, but only requests 1 packet about once every hour if you allow just that port through. I was able to confirm it retains the setting by:

1. Enabled debug tracing and noticed the timezone was still "America/Los_Angeles" despite the field being empty in the Web UI.
2. I switched it to "US/Pacific" and reloaded the integration (not sure if necessary), then rebooted HA, and debug tracing reflected "US/Pacific."
3. I then cleared the timezone setting again and did the same thing - reloaded the integration, rebooted HA, enabled debug tracing, and it retained the US/Pacific. setting.

(Debug tracing logs attached)
[msg100-1632093061.csv](https://github.com/krahabb/meross_lan/files/7193215/msg100-1632093061.csv)
[msg100-1632093469.csv](https://github.com/krahabb/meross_lan/files/7193216/msg100-1632093469.csv)
[msg100-1632092798.csv](https://github.com/krahabb/meross_lan/files/7193217/msg100-1632092798.csv)

I tried looking through the code to see if I could somehow clear it but was unsuccessful, but I did notice something else.

It seems the integration is using "pytz" and for future proofing this addon, according to this:

https://developers.home-assistant.io/blog/2021/05/07/switch-pytz-to-python-dateutil/

HA 2021.6 switched from "pytz" to "python-dateutil" (EDIT: "zoneinfo" - see the bottom of the link above) so while it still works for now, it's probably best to switch for the sakes of future proofing the addon before it breaks in an HA update someday. Not sure if this was already in the plans but thought I'd bring it up just in case.

**Comment by krahabb** [comment] 2021-09-20 08:12
Thank you @jaytea33 ,
the 'empty' TimeZone not updating is 'by design' but obviously in need of rethinking. 
The idea was: TimeZone 'blanked' in configuration -> don't configure it or touch in any way
Now this is ok when you start blank but if you want to go blank in the device there's no option to do that. I'll refactor this a bit

As per pytz I remember choosing that over dateutil because it seemed more fit at the time but I'll check and port my code to dateutil anyway based on your report since I know for sure (some users issues) pytz might not be there and I don't expose any dependency in my manifest so my timezone code works only when pytz is present failing gracefully if not.

**Comment by jaytea33** [comment] 2021-09-21 03:06
Thanks krahabb, looking forward to the eventual update (no rush, I realize you do this on your own personal time). I'll leave my environment as-is currently so I can confirm the issue is fixed once it's implemented.

Also, regarding pytz, I missed it before but it seems "dateutil" has been removed as well and that "zoneinfo" should be used instead. The bottom of the link above shows the following:

"...Python 3.9 includes upgraded timezone handling and we should use that instead. With the help of Nick and Paul python-dateutil has been removed again and zoneinfo is used instead"

**Comment by krahabb** [comment] 2021-09-21 04:13
Yeah, I've read that too after your comments. I had the time to look back at my code and tried to port it to zoneinfo but there's a 'special' info in pytz I'm using and that's why I decided for it in the first place..let's see
I too would prefer to 'align' and don't rely on an external library but that feature I'm using from pytz is not clearly available in zoneinfo (even dateutil for the matter lacks it)

**Comment by jaytea33** [comment] 2021-09-21 18:20
Hi Krahabb,

Thanks for the quick work on this. Unfortunately the device is still reaching out via Port 123, I'm starting to wonder if the MSG100 requires it. The timezone does now appear blank though (debug log attached)


[msg100-1632248450.csv](https://github.com/krahabb/meross_lan/files/7205321/msg100-1632248450.csv)

Here are the blocked NTP requests from my router's logs:

DST=72.30.35.88 LEN=76 TOS=0x00 PREC=0x00 TTL=254 ID=15119 PROTO=UDP SPT=61910 DPT=123 LEN=56
DST=203.107.6.88 LEN=76 TOS=0x00 PREC=0x00 TTL=254 ID=15117 PROTO=UDP SPT=61910 DPT=123 LEN=56
DST=204.11.201.12 LEN=76 TOS=0x00 PREC=0x00 TTL=254 ID=15111 PROTO=UDP SPT=61910 DPT=123 LEN=56
DST=38.229.58.9 LEN=76 TOS=0x00 PREC=0x00 TTL=254 ID=15109 PROTO=UDP SPT=61910 DPT=123 LEN=56
DST=129.250.35.250 LEN=76 TOS=0x00 PREC=0x00 TTL=254 ID=15121 PROTO=UDP SPT=61910 DPT=123 LEN=56

Note that I have tried rebooting the router, rebooting the AP, reloading the integration, rebooting entire HA host, and killing power to the device via my home's power panel, all with the same result. If you have any suggestions, please let me know, but I've re-allowed outbound UDP port 123 for now again so that it doesn't spam NTP requests.

**Comment by krahabb** [comment] 2021-09-22 05:40
I guess we cannot set a 'definitive' rule/behaviour on how these devices work.
Personally, in my initial testings, after reading https://github.com/albertogeniola/MerossIot/issues/142, I thought I 'had' to let NTP flow through my firewall and that's what I did. Then, after a while, by error, I understood some devices were booting and working almost correctly even when blocked on a full insulated LAN.

I've never checked what they are doing at the network level since ...they were working good anyway and I was not really interested in a full 'regression' especially since, like I said, every device/firmware might introduce changes.

Also tbh there a lot of devices beside these Meross, trying to 'spam' (it's not really spamming: it's just trying to connect to some server, sometime, someway). As far as they're blocked, they're not 'overloading' the network or the router, and the device keeps working I don't think that's an issue per se

Like @albertogeniola suggests, it would be ideal to configure the router to 'intercept/redirect' these NTP requests to a local NTP service (the router itself) and maybe there are routers able to easily be configured these way. I have a FritzBox and, even though I expected it was able to implement a sort of automatic filtering-redirection of NTP it is not so I'm left with some manual tricks which I never managed to implement...

I would 'attach' to your list of possible fixes also these 'tricks':
- customize the router routing table so to direct those external NTP servers IP to a local machine (not sure if it would work without also 'masquerading' these IP's)
- better: if the Meross are 'resolving' standard NTP server names before actually trying to connect to them (I only see logs for NTP so I don't know if the DST addr is fixed in firmware or resolved by DNS before connecting), you can likely configure your LAN to provide basic DNS (it is almost always a good idea though for a lot of reasons) and configure it to 'redirect' those public server names to (again) a locally provided NTP service (like the router itself). This is also the idea suggested by @albertogeniola and I find it the most elegant and functional: just a bit of network configuration with your own DNS server

**Comment by jaytea33** [comment] 2021-09-23 00:40
I was able to redirect "pool.ntp.org" on my edgerouter 4 by setting a DNS rule to point to my HA server running Chrony and I'd agree that's probably the easiest workaround. Problem is Chrony by default uses "pool.ntp.org" so it would essentially be a loopback if left that way, so I changed Chrony itself to use "time.windows.com" and now the MSG100 is no longer desperately reaching for NTP. I do realize it doesn't affect the device or cause issues but it realllly tries to reach out and while I have the router set to Drop rather than Reject for performance, I just hate seeing a device I've attempted to block all internet access to try to reach outside the LAN lol. It won't be a great fix for everyone but for me, this DNS rule suffices for my needs.

**Comment by krahabb** [comment] 2021-09-23 04:49
> I just hate seeing a device I've attempted to block all internet access to try to reach outside the LAN lol.

I totally agree. I too would like to have everything smooth and clean but...sometimes it is just not possible (with a reasonable effort)
I think this 'dns redirect' is quite a nice trick and it could come to be useful for many other behaviours too (think of ip cameras which also use NTP: I have some on a private LAN and their time is random...still have to fix them since I don't managed yet to setup my private dns)
Thank you for confirming this is a viable scenario and keep up!

**Comment by Joshndroid** [comment] 2021-11-05 09:20
I also noticed that the devices spam the ntp logs in the dns server. I have done as suggested and basically rerouted the ntp to a local domain running a slighly different pool... curious on why it needs to hit it so many times though

**Closed** 2023-01-27 20:36 UTC
Labels: enhancement, fixed
