### ISSUE TITLE
Unable to get sensor values from MSS310 (similar to closed #300)

### ISSUE THREAD

**Issue by BillKen** [krahabb/meross_lan#318] opened 2023-09-17 06:17 UTC
"0" returned for sensor values for 2 new devices added to meross_lan with 4 working older devices:  possibly the same as #300 which was closed as it started working ...

## Version of the custom_component
Version in manifest.json is 4.3.0

## Configuration

No yaml, configured via GUI

## Describe the bug

I have a long running instance of meross_lan with 4 MSS310's which are working as expected (MQTT, Firmware: 6.1.10). I have tried to add 2 newer MSS310 (Firmware: 6.3.21) and while the actual switch can be controlled the monitoring sensors are "0" despite all attempts to reconfigure, restart etc. for over 2 weeks now. Timezone has been set, wireshark seems to show ntp working and debug logs have timestamps.

## Debug log

[meross_lan-ffabbc2f0dd3f3d78a562515aaece333-Smart Plug (2302026313430151070148e1e9b8fbdb)-bd4cf088d7ddab301d55f82fcd9a5d0a.json.txt](https://github.com/krahabb/meross_lan/files/12642168/meross_lan-ffabbc2f0dd3f3d78a562515aaece333-Smart.Plug.2302026313430151070148e1e9b8fbdb.-bd4cf088d7ddab301d55f82fcd9a5d0a.json.txt)

[mss310-1694922767.csv](https://github.com/krahabb/meross_lan/files/12642170/mss310-1694922767.csv)

```

**Comment by krahabb** [comment] 2023-09-18 12:29
Hello @BillKen,
Since this is only happening on the 2 newer firmwares it might be a 'glitch' related to this.
I've taken the time to check the trace/logs and I see there's a possible issue in how the timezone informations are set on the device.
Specifically, when devices (in meross_lan) are locally MQTT binded and you set a timezone in configuration (which should be the case from what I understand of your setup) meross_lan needs to take care of setting the appropriate timezone offsets and daylight saving epochs for the devices so they're 'aware' of the correct local time. This in turn is needed since the mss310 need to synchronize to midnight (local time) in order to correctly reset it's own energy sums.

By the traces I see this configuration is partially 'broken' ("timeRule" array in the json trace at line 228) and this is because meross_lan uses the (deprecated/legacy) python module 'pytz' in order to calculate the daylight saving time epochs and you're likely missing this package on your system. HA itself used to install it but it is likely no more a requirement. For meross_lan itself is kind of a 'soft' requirement so it just tries to use it if present, failing (almost) graciously when unavailable. If this happens the calculations for the DST are not carried over and the device configuration is just a 'best effort'.

I'm not sure this is the reason for the issue but it could be (as I've said, different firmwares might be more or less robust against this)

The first 'level' of patching would be to manually install the 'pytz' module in your HA environment and see if this fixes it. I'm aware of this possibly failing dependency on 'pytz' for meross_lan and I've always delayed taking care of it but I guess I'm going to raise the urgency for patching the code.

I'll wait for your reply and start working on it, maybe sooner than later a fix will come through

**Comment by BillKen** [comment] 2023-09-18 13:14
Thank you Krahabb, It will be a day until I can get back to it but I have dev-python/pytz and dev-python/pytz_deprecation_shim already installed.

However, I found a way to make it work:
1. configure the MSS310 as MQTT and with TZ as expected
2. set MSS310 to off, then remove the power from it
3. wait 30 seconds
4. apply power and wait until it connects to wifi
5. immediately operate switch button (before it connects to HA), the DND LED in the button will go red for a couple of seconds before going green
6. In HA it should now show the metered values.

I did this twice on one switch and once on the other!  Sounds flaky and I have not tried to really verify that it works reliably as the MSS310's are being used at the moment. Perhaps someone else having problems could try this method?  Is it useful to get a new set of debug logs now they are working?

BillK

**Comment by BillKen** [comment] 2023-09-25 02:26
Something I just noticed if you suspect the DST handling code - I am using the timezone Australia/Perth which does not use daylight saving unlike some other states/locations in Australia. Does this affect the DST calculations?
BillK

**Comment by krahabb** [comment] 2023-10-10 13:55
Well done indeed!
It's hard to know the real reason but, as far as I can remember, this issue was almost always related to the device being incapable of correctly setting its own time: either because no NTP source were available (at boot) or maybe for an incorrect timezone setting.
nevertheless I'm going to modernize the pytz dependency in order to make it more stable in the future

**Comment by Superperforator1337** [comment] 2023-10-20 18:27
Hey, will there be a fix soon?
Many of my automations dont work because of this issue :(
Tried BillKens fix but it did not work unfortunately

**Comment by krahabb** [comment] 2023-10-21 06:30
Hello @Superperforator1337,
The only planned work in order to try fix the mss310 not reporting any power/energy reading is to refactor the code that now depends on `pytz` library since it is likely failing in modern HA distributions.

At any rate, it would be nice to have a device [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) for the malfunctioning device for me to check the problem is really the same

In fact, as of my knowledge, the device could fail to provide the readings also when it doesn't properly receive the correct time through its own NTP feature. Having a device trace could help me check for this and every other possible issue.

**Comment by Superperforator1337** [comment] 2023-10-21 08:48
For some reason i cannot download the diagnostics, it fails to download every time.
I will try to get it running.
For your information, i do have mss210p and mss315, both dont provide the data. 
I began with the mss210p, it worked for some weeks until it suddenly didnt anymore. 

2 weeks ago i installed one mss315, it provided data the first few minutes then it stopped and i can only turn on and off.

Thank you for your help!

**Comment by Superperforator1337** [comment] 2023-10-21 09:15
Here is the diagnostics file from one of the devices

[meross_lan-543877156fea423f31a84b2db93e5370-Smart Switch (23022304262818510d0248e1e9bb787e)-b708ae7a190543b04f7b67af5e797059.json.txt](https://github.com/krahabb/meross_lan/files/13060360/meross_lan-543877156fea423f31a84b2db93e5370-Smart.Switch.23022304262818510d0248e1e9bb787e.-b708ae7a190543b04f7b67af5e797059.json.txt)

**Comment by Superperforator1337** [comment] 2023-10-21 09:36
I just re-added the devices in the meross app and this fixed the issue.
They are still connected via Meross_Lan, i dont have my meross account configured in home assistant.
Maybe this helps. I'd still like not to use the meross app to get these values if this is possible.
Anyway thank you for helping with this issue.

**Comment by krahabb** [comment] 2023-10-22 13:04
Hello @Superperforator1337,
thank you for your efforts.

The official diagnostic button from HA UI doesn't work if you browse your HA instance through a reverse proxy (like NabuCasa for the matter) while should work if you acces it locally

The trace you provided is for an mss210 so we could focus on this device. Everything looks good there (the consumption values are in the trace) and I expect you can see the energy/power readings in HA too at the moment.

I see it has no timezone configured so it is now (or I guess so..) working with UTC time: this should in turn reset your daily energy readings at midnight UTC. Please confirm this is the case so we have a 'solid' common knowledge of the actual behavior.

Once this is established, could you please return the device to your previous configuration (the one which was not working correctly) and then collect another trace ?

Thank you for your collaboration!

**Comment by Superperforator1337** [comment] 2023-10-24 15:19
Right now I do not have the time to do it, but I will provide the trace in the coming days!

**Comment by krahabb** [comment] 2023-10-29 08:22
Duplicate of #300

**Closed by krahabb** 2023-10-29 08:22 UTC
Labels: bug
