### ISSUE TITLE
MerossKeyError in async_http_request

### ISSUE THREAD

**Issue by galamarco** [krahabb/meross_lan#256] opened 2023-02-07 16:58 UTC
Hello, 
I have a a Meross MSS310H device that is connected to the network and reachable from the Meross app but Home Assistant detects it as unavailable.
Downloading the logs I found this:

```
"2023/02/07 - 17:45:21",
        "",
        "auto",
        "LOG",
        "WARNING",
        "MerossDevice(Misuratore fornelli) MerossKeyError in async_http_request: "
```

Hardware version mss310h 3.0.0
Firmware: 3.1.1

![](https://www.webg.it/images/articoli/2018-06/Screenshot_2_p50978.png)

How can I fix?

Thanks a lot.

Best regards
Marco

**Comment by krahabb** [comment] 2023-02-07 18:32
Hello @galamarco,
Just enter the integration configuration and set the proper 'key'.
You likely have an empty value there since previous versions of meross_lan allowed this to work with an hack.
This 'feature' has been removed in order to stabilize devices configuration and reliability so you now have to provide the correct key in configuration.
If your device is paired to the meross app just save the configuration with the blank or any 'wrong' value for the key and it will prompt you to recover the correct key from your meross account.
If your device was instead re-paired to a custom MQTT broker you should know the device key yourself since this configured during the pairing process

**Comment by kaciker** [comment] 2023-02-10 19:10
> Hello @galamarco, Just enter the integration configuration and set the proper 'key'. You likely have an empty value there since previous versions of meross_lan allowed this to work with an hack. This 'feature' has been removed in order to stabilize devices configuration and reliability so you now have to provide the correct key in configuration. If your device is paired to the meross app just save the configuration with the blank or any 'wrong' value for the key and it will prompt you to recover the correct key from your meross account. If your device was instead re-paired to a custom MQTT broker you should know the device key yourself since this configured during the pairing process

Hello, I have the same situation. I delete the device because with reconfiguring anythin happend.
I create again the device, set the IP, and go to recover key from cloud Meross. THe key is coming back 
![image](https://user-images.githubusercontent.com/7668181/218176656-08d79290-df8d-4448-a334-0d6f2bc82bdb.png)

But after that, when i click "send" I receive the error "error key device" and I enter in a loop...
![image](https://user-images.githubusercontent.com/7668181/218176815-4d6c93e3-dd09-4061-82d0-892e39970396.png)

I have two mss425f devices and have the same probem with two, appearing in the last upgrade to V3.0.1. What can I do ?

**Comment by krahabb** [comment] 2023-02-11 08:29
Hello @kaciker,
If your device is working correctly with the Meross App then the key you retrieved is correct and 'should' work.
Maybe the issue is an IP connectivity problem.
Does the HA log reports any warning or error from meross_lan ?
I'm also curious as to why the last screen IP changed, was that a different try with another device ?

**Comment by kaciker** [comment] 2023-02-11 15:48
Hello, thansk for your answer
I've two devices, with IP 192.168.31.115 and 167. I deleted the device with Ip 115, and now is not reconished in Moross neither., this corespond with the second screenshot sent.
The first is the one IP 167, that I didn't deleted, is offline in HA, but online in APP Meross. I have both IP's fixed in my router, and I checket it with the mac that is correct

For the online 167, I tried to reconfigure
![image](https://user-images.githubusercontent.com/7668181/218267210-54c259a8-dde1-498e-b282-cb9ab173dedd.png)
I set my user/pasword Merros, and it give me the key, but when I clik in send I have the same erorr
Error in device key
![image](https://user-images.githubusercontent.com/7668181/218267258-bf7f3f59-e339-49d8-8f70-f846351b902c.png)

I checked the log HA, but there are not info about Meross

**Comment by kaciker** [comment] 2023-02-11 16:04
HI, I have a second HA in a rasp4, I installed the integration, and just after restart, the Merros (online in MEross app) is discovered. I set the user/password for app meross, and comeback with the key, but oafter that I have the same issue

![image](https://user-images.githubusercontent.com/7668181/218268253-40ee8447-3e0a-4e25-90d9-f4b771cb1690.png)

**Comment by krahabb** [comment] 2023-02-12 10:23
I can't really figure out what's going on.
I've tried digging around for the likely cause and the only thing coming up is the fact the hashlib.md5 function in python might fail or be blocked for security reasons in your setup but I guess it's very unlikely (or not?)
The md5 function is used to calculate the message signature for the meross protocol but since it's an old 'insecure' algorithm, newer environments (linux kernel or so...) might prevent it from working (FIPS mode compliance)
Might this be the case ?
From what I've read, for example, if a linux kernel has been compiled to be FIPS compliant it might refuse to calculate the md5 hash. But you have 2 systems showing the same behavior, I hardly think this is the case but maybe this hints to something...

**Comment by kaciker** [comment] 2023-02-12 18:19
> I can't really figure out what's going on. I've tried digging around for the likely cause and the only thing coming up is the fact the hashlib.md5 function in python might fail or be blocked for security reasons in your setup but I guess it's very unlikely (or not?) The md5 function is used to calculate the message signature for the meross protocol but since it's an old 'insecure' algorithm, newer environments (linux kernel or so...) might prevent it from working (FIPS mode compliance) Might this be the case ? From what I've read, for example, if a linux kernel has been compiled to be FIPS compliant it might refuse to calculate the md5 hash. But you have 2 systems showing the same behavior, I hardly think this is the case but maybe this hints to something...

I solved the problem.. but is complex to understand how I can failed in this way. When I created my Meross account I setuped my mail xxxx@gmail.com, but by mistake I wrote xxx@gmail.con.   it seems that Meross did not sent any mail confirmation...  Now I was cehcking in the parameters of the app looking for something to solve this issue... and i saw taht.  I changed the mail for something correct and it's working.  That I don't understand is how was posible when I requested for the key that did't fail becasue I used the correct .com adress.... 

sorry for the inconvenence.

**Closed** 2023-04-30 05:41 UTC
Labels: wontfix, suspended
