### ISSUE TITLE
MSG100 slow to respond and other issues

### ISSUE THREAD

**Issue by AlaaShaker** [krahabb/meross_lan#82] opened 2021-09-19 06:50 UTC
Hi - Thanks for the integration. I have a garage door opener (MSG100) that's already integrated with HA through the Meross Cloud integration. I was looking at this integration instead hoping to get local, faster updates. Took me a while to figure out the device key, but finally got it to work successfully and now I can control the garage door through either integration.

I'm noticing few issues with the LAN integration:

1. It's much slower to detect state changes than the Cloud integration. I assumed it would be the other way around.
2. The "opening" state apparently relies on the "transition_duration" attributes, which is set to 35 seconds. This is way too long for my garage door. I've even set it to 10 seconds in the official Meross app. I can't figure out a way to change it in HA.
3. Minor - It switches between "opening", "open", and "closed" states, but there's no "closing".

Any thoughts? Thanks again!

**Comment by krahabb** [comment] 2021-09-19 09:22
Hello @AlaaShaker 
Thank you for your comments here. I understand your expectations for a 'local faster integration' but, it's not or well, depends:

It really comes down to how you integrate devices in meross_lan: you can either use MQTT (private broker: be it in lan or on the cloud) or HTTP for a direct connection to devices.
Connecting through HTTP is relatively easy and fast (meaning the connection is fast, surely the fastest) but has 1 big caveat: it's a request/reply (HTTP1/1 that's it) protocol so there's no 'PUSH' from the device to update state (which instead works on MQTT).
meross_lan then uses a polling mechanism to periodically query the state (by default every 30 sec: you can change this down to 5 sec).
This way you should notice 'blazing fast' commands sent from HA being executed but 'lazy' state updates

When you use MQTT to connect to devices you'll instead get instant PUSH updates from them (with the typical latencies of MQTT : from  hundreds msec to some seconds if the broker is 'far and overloaded'.

the Meross Cloud integration you are using works by connectint to the official MQTT brokers and so it is able to receive state updates with that kind of latencies (I guess in the order of 1-2 sec).
meross_lan can connect to a private MQTT broker if you follow the [procedures](#63) to re-pair your devices: this way you'll 'loose' the App and the official cloud features but you'll get total and almost instant control (by the look of the issues with MQTT setup it might be a nightmare or not: depends on your skills and the overall MQTT architecture if there's one in place in your HA setup)
meross_lan can't connect to the official Meross brokers: it was never intended to work that way since there is already Meross Cloud and it would be a duplicate.

Now to MSG100 :)
I had the option to test the MSG100 with a 'fellow contributor' (we did some online remote debug sessions since I don't have any) and came up with some insights about the device and how it is integrated:
the device itself usually just sends inching commands (through a dry relay contact) to an external garage controller so the timings and stuff are totally 'out of control'. More, depending on the logic of the garage controller, and the presence of other input commands like remotes or so, it could happen you send a command to close the garage while it effectively opens it (it happened the garage was stopped halfway by the external command and the meross reported it opened so when sending a new inching command we thought it was going to close while instead the internal state of the garage controller was expecting an open command: this happens when garage controllers ar set for an inching sequence working like 'open'-'stop'-'close'-'stop'

Just to say: it can't reliably report state if integrated that way since the garage is controlled by an external logic and MSG100 only does this:
- report a contact stating if the door is (fully) closed
- send an inching command

This is true for the app too: in the end, after some timeout, it reports the state of the contact (and you can 'fool' the app the same way by using the extranl remote for the garage if any)

meross_lan uses the same contact information to report the actual state and uses it's own timeout to manage transitions and guess where the garage is going; but this guess is only working when you (meross_lan on HA) start the transition and to a lesser extent when the transition is started externally (by app or remote)
In more details: the device just exposes the contact state: if the garage is being closed externally we'll not get any 'new' state information until the door contact closes which is usually at the end of the transition and that's why I can't report the 'closing' transition when started externally: meross_lan gets updated only when the transition is over :(
When the garage is being opened I'm instead using this information to try and guess an 'opening' transition since the contact state change happens soon at the start of it.

Regarding the 'transition_duration' attribute you're right it might not be correct but meross_lan uses it's own initiated transitions to automatically 'learn' this duration and provide and use this estimate. You should see this by repeating a bunch of open/close transitions started from meross_lan and see this attribute updating and approximating (hopefully) the correct real timings.
Of course, when you restart HA this calculations get lost and the 'transition_duration' will restart from default.

The algorithm there is not really tested in the wild so it might not work as explained :(

If you're up to some 'contributions' I'm open to the discussion in order to better refine this behaviour but, as stated, we did an almost complete regression of msg100 behaviour and came up to this in the end. As per using the App configured timeouts it could be in some way a nice feature so I would need some [debug traces](https://github.com/krahabb/meross_lan#troubleshooting) with a little explanation of the actions taken being it commands from HA or commands issued externally through remotes or the Meross app and the 'real' outcome of these actions

**Comment by AlaaShaker** [comment] 2021-09-19 09:45
Thanks, @krahabb, for the detailed explanation. 

RE the slow responses - I don't think I know enough (yet) to go through the private MQTT route on my own, and I don't think the HTTP route would yield better results than the Cloud integration. BTW, the link to the "procedures" in your response is broken. I think I'm gonna stick with what I have for the time being, particularly since I want to keep the official app.

RE the states - That makes perfect sense now, thanks for the explanation. And you're right, the app doesn't do much better either. One way that might fix that is having a couple of contact sensors attached to the garage. They can be used to report whether the garage is fully opened or closed without relying on timeout estimates. They also allow faking 'opening' and 'closing' states based on which contact sensor just got tripped. And optionally, a timeout could be used to detect if the garage didn't make it all the way to the other end. I'm gonna look online to see if someone has something like that implemented already, or try to do it myself otherwise.

RE the `transition_duration` - I haven't monitored it closely to see if the value changes, but even if it did, it's a shame that the value is lost when HA gets rebooted. Is there a way to expose this value as a configuration (i.e. the HA user can manually set it to 10 seconds for instance)?

I'd be more than happy to collaborate or send you logs if that helps, but it seems you've already done a great job pushing this to its limit already :)

**Comment by yagrasdemonde** [comment] 2021-09-20 13:00
Yes, I'm agree with @AlaaShaker to set and save transition duration value in configuration. Home Assistant can restarts many times per week (updates, custom components testing, and so...)
I have 3 MSG100, 2 for garages doors and third for my gate. So if i can help too, I will be happy

**Comment by TheOneOgre** [comment] 2022-03-25 01:37
Has this been forgotten about? Seems as if no matter the setting in the config flow, the transition_duration always sets to 35

**Comment by krahabb** [comment] 2022-03-25 07:49
Hello @TheOneOgre ,
Last version of meross_lan gives you control over the 'Open/Close' duration config as they are in the app itself. The transition_duration is initialized halfway between the 2 on startup so, the 35 is likely the mean between the two.
You can manually change these values on the device page in HA in order to better suit your needs and set the correct value for your garage (or change them in the app which is the same).
Sadly enough, I've just developed and tested this feature on an emulated device so I'm not really sure it works like this but I'm pretty confident.

Also, I'm working on restoring the previous state for garage and shutters so to have these 'volatile' values restored through HA restarts anyway, but this will come on the next release.

**Comment by TheOneOgre** [comment] 2022-03-25 17:52
> Hello @TheOneOgre , Last version of meross_lan gives you control over the 'Open/Close' duration config as they are in the app itself. The transition_duration is initialized halfway between the 2 on startup so, the 35 is likely the mean between the two. You can manually change these values on the device page in HA in order to better suit your needs and set the correct value for your garage (or change them in the app which is the same). Sadly enough, I've just developed and tested this feature on an emulated device so I'm not really sure it works like this but I'm pretty confident.
> 
> Also, I'm working on restoring the previous state for garage and shutters so to have these 'volatile' values restored through HA restarts anyway, but this will come on the next release.

So in the Meross app, the duration is set to 15 seconds, so I'm not sure where the 35 is coming from. 

In the device configuration, the polling interval is set to 15, but it takes the full 35 seconds for a complete cycle change (e.g. Closed>Closing>Open) and the status to update.

I've tried reconnecting the integration and get the same result. I am willing to help debug if necessary.

**Comment by GeneralErrors** [comment] 2022-04-22 20:21
I am experiencing a similar issue ... using the Meross opener for 2 gates.  Tried to update the  doorCloseDuration and doorOpenDuration and neither can be modified.

I did update to the pre-release version and noticed the timer is now being held across reboots but it would be nice to edit this setting and have it hold instead of using the automatic method it is currently.  I am hoping being able to update this transition timer will allow me to hold the gates open - as they auto close and will not accept a second input during this transition hold.

Thanks for your work guys - much appreciated.

**Comment by patrickli** [comment] 2023-02-08 19:29
I'm sorry but why is this closed? I'm seeing exactly behaviour as @TheOneOgre reported for `doorCloseDuration` and  `doorOpenDuration`. `signalDuration` is the same as set in the app and is changeable.

It would solve this ticket if these values are user changeable or can be polled from the device (there is a setting in the app, but it might not be saved on the device).

**Comment by krahabb** [comment] 2023-02-09 10:30
Hello @patrickli,
This was closed due to being stale so I'm sorry for the issue to still be there.
Since I don't have any real msg100 to test I need feedback on the issue from users in order to fix it. From a quick review I see the code is still lacking some steps in order to fix this issue so I've likely forgot to complete the implementation at the time :(

As stated before, in meross_lan you should be able to see and control the garage door timeout (plus some other device features) through the Configuration entities you find on the device page.
If these 'doorCloseDuration' and 'doorOpenDuration' entities are working good (i.e. you should see the same values as in the app and you should be able to change these values and see them change in the app) then it's just (blame) on me to complete the implementation in order to use these values instead of the infamously hardcoded '35'.

I'll wait your confirmation these entities are working as expected in order to consider them 'good' while I start working on the necessary patch for these values to be 'actively' used instead of the hardcoded default

**Comment by patrickli** [comment] 2023-02-09 21:20
Much appreciated. So to summarise:

* `doorCloseDuration` and `doorCloseDuration` values are empty and non-modifiable.
* There is an "Opening Time" value you can set in the app.

Hope the above information is useful.

**Comment by AlaaShaker** [comment] 2023-02-09 22:47
I can confirm that I'm seeing the same - both `doorCloseDuration` and `doorCloseDuration` entities are unavailable and non-modifiable in Home Assistant. 

FWIW and perhaps unrelated, the Alexa integration with Home Assistant for the garage door doesn't account for opening or closing times. So if I say "Alexa, close _garage door_", it responds, "Closing _garage door_. _Garage door_ has closed." (both statements back to back with no pause), while the garage door is still closing for the next 10s or so.

**Comment by krahabb** [comment] 2023-02-10 06:41
> Much appreciated. So to summarise:
> 
> * `doorCloseDuration` and `doorCloseDuration` values are empty and non-modifiable.
> * There is an "Opening Time" value you can set in the app.
> 
> Hope the above information is useful. I am reasonably technical so can help you run some diagnostics if needed.

Maybe the device api is a bit changed or who knows....
I really need a [diagnostic trace](https://github.com/krahabb/meross_lan/wiki/Diagnostics#download-diagnostics) to see what the device is 'offering' and try tinkering with that

While tracing is active please try to 'operate' the device entities from HA (all of the configuration entities so I can have a look at what is working and what not when the device receives these values)
When operating the entities do that at a 'reasonably slow' pace around 4-5 seconds between each UI interaction so the trace is easier to read should any of these interactions start logging protocol errors or timeouts

Thank you!

**Comment by patrickli** [comment] 2023-02-11 06:30
Cool I will do that sometime. Do I need to tick "Activate device debug tracing" checkbox in the configuration?

**Comment by krahabb** [comment] 2023-02-11 08:31
Yes, but using the diagnostic option from the HA interface for the device would be easier. The 2 tracing options collect exactly the same data, just different setup and file format

**Comment by patrickli** [comment] 2023-02-11 22:47
There you go.

[config_entry-meross_lan-3fbfb92af89a4064ee1ae9079bf8c249.json.txt](https://github.com/krahabb/meross_lan/files/10714855/config_entry-meross_lan-3fbfb92af89a4064ee1ae9079bf8c249.json.txt)

**Comment by krahabb** [comment] 2023-02-12 12:10
Well,
from the first quick inspection the two parameters (door open/close) are not reported anymore (!?) by the device api. This is hard to overcome without deeply testing the device.

To go further technical:
The garagedoor configuration is carried in the `Appliance.GarageDoor.Config` message which is reported like this in your trace:
```
{
    "config": {
      "signalDuration": 1000,
      "buzzerEnable": 0
    }
}
```
while it used to be:
```
{
    "config": {
      "signalDuration": 1000,
      "buzzerEnable": 0,
      "doorOpenDuration": 30000,
      "doorCloseDuration": 30000
    }
}
```
in older firmwares.
Actually this is unsurprising since the open/close timeouts should be configurable per channel (the garagedoor family of devices has also multi channel units) and the older format was not able to carry/manage this configuration 'per channel'

I suspect Meross moved these parameters to a more structured payload but there are no other meaningful messages in the exposed abilities for the matter so I guess we should stick to this message and try to query this with different strategies.

If you would like to try, you could use the meross_lan.request service to query the device like this:
```
device_id:  your garagedoor UUID
namespace: Appliance.GarageDoor.Config
method: GET
payload: '{ "config": [ { "channel": 0 } ] }'
```
and see if this request is understood and correctly peeks the configuration for channel 0 on your device.
There's one caveat though, the service call will not show you the response (I've never tried to overcome this limitation with any sort of trick) so the only way, actually, is to enable debug log for meross_lan or issue the service call while the device is under diagnostic/tracing so the response get logged in the trace file

**Comment by patrickli** [comment] 2023-02-12 23:30
I ran this a couple times. Here is what I got. Results are all similar and there is nothing related to the opening/closing time.

```
2023/02/13 - 12:20:53   TX      http    GET     Appliance.System.All    {"all": {}}
2023/02/13 - 12:20:53   RX      http    GETACK  Appliance.System.All    {"all": {"system": {"hardware": {"type": "msg100", "subType": "us", "version": "3.5.0", "chipType": "mt7682", "uuid": "################################", "macAddress": "#################"}, "firmware": {"version": "3.2.7", "compileTime": "2022/08/30 12:14:18 GMT +08:00", "encrypt": 1, "wifiMac": "#################", "innerIp": "##############", "server": "####################", "port": "###", "userId": "#######"}, "time": {"timestamp": 1676244053, "timezone": "Pacific/Auckland", "timeRule": [[1664028000, 46800, 1], [1680357600, 43200, 0], [1695477600, 46800, 1], [1712412000, 43200, 0], [1727532000, 46800, 1], [1743861600, 43200, 0], [1758981600, 46800, 1], [1775311200, 43200, 0], [1790431200, 46800, 1], [1806760800, 43200, 0], [1821880800, 46800, 1], [1838210400, 43200, 0], [1853330400, 46800, 1], [1869660000, 43200, 0], [1885384800, 46800, 1], [1901714400, 43200, 0], [1916834400, 46800, 1], [1933164000, 43200, 0], [1948284000, 46800, 1], [1964613600, 43200, 0]]}, "online": {"status": 1}}, "digest": {"togglex": [{"channel": 0, "onoff": 1, "lmTime": 0}], "triggerx": [{"channel": 0, "id": "1111111111111111", "count": 2}], "timerx": [{"channel": 0, "id": "1111111111111111", "count": 1}], "garageDoor": [{"channel": 0, "open": 0, "lmTime": 1676235864}]}}}
2023/02/13 - 12:20:53   TX      http    GET     Appliance.GarageDoor.Config     {"config": {}}
2023/02/13 - 12:20:53   TX      http    GET     Appliance.System.DNDMode        {"DNDMode": {}}
2023/02/13 - 12:20:54   RX      http    GETACK  Appliance.GarageDoor.Config     {"config": {"signalDuration": 1000, "buzzerEnable": 0}}
2023/02/13 - 12:20:54   RX      http    GETACK  Appliance.System.DNDMode        {"DNDMode": {"mode": 0}}
```

**Comment by krahabb** [comment] 2023-02-13 11:26
I've searched around the internet and I think I've found what the possible solution is. It looks like there's a 'new' protocol message (which your device doesn't expose in its supported capabilities list though - maybe at meross prefer to keep this 'hidden :)

I'm trying to release a new version with some work in this direction but I'd need to know if this command works and how it looks like so you could try again, using the Developers tools service UI to send this message:
```
device_id:  your garagedoor UUID
namespace: Appliance.GarageDoor.MultipleConfig
method: GET
payload: '{ "config": [ ] }'
```
again, we'd need either debug logging enabled or tracing enabled for the reply to get logged so we're able to see the results

**Comment by patrickli** [comment] 2023-02-14 01:29
Does seem to response to this namespace.

```
2023/02/14 - 14:25:42   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {"config": []}
2023/02/14 - 14:25:42   TX      http    GET     Appliance.Control.ToggleX       {"togglex": []}
2023/02/14 - 14:25:42           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(0): Server disconnected
2023/02/14 - 14:25:42   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {"config": []}
2023/02/14 - 14:25:43           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(1): Server disconnected
2023/02/14 - 14:25:43   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {"config": []}
2023/02/14 - 14:25:43   RX      http    GETACK  Appliance.Control.ToggleX       {"channel": 0, "togglex": {"channel": 0, "onoff": 1, "lmTime": 0}}
2023/02/14 - 14:25:43           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(2): Server disconnected
2023/02/14 - 14:25:44   TX      http    GET     Appliance.Control.TimerX        {"timerx": {}}
2023/02/14 - 14:25:46   TX      http    GET     Appliance.Control.TriggerX      {"triggerx": {}}
2023/02/14 - 14:25:48   TX      http    GET     Appliance.GarageDoor.State      {"state": {}}
```

Tried with an empty payload as well.

```
2023/02/14 - 14:26:35   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {}
2023/02/14 - 14:26:35           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(0): Server disconnected
2023/02/14 - 14:26:35   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {}
2023/02/14 - 14:26:35           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(1): Server disconnected
2023/02/14 - 14:26:35   TX      http    GET     Appliance.GarageDoor.MultipleConfig     {}
2023/02/14 - 14:26:36           auto    LOG     INFO    MerossDevice(Garage Door) ServerDisconnectedError in async_http_request attempt(2): Server disconnected
2023/02/14 - 14:26:40   TX      http    GET     Appliance.System.All    {"all": {}}
```

**Comment by krahabb** [comment] 2023-02-14 11:24
Well..I'm very sorry but this is expected since the namespace is not listed in the device abilities.
I've found this 'new' message namespace in the merossIoT library from @albertogeniola (which I often dig into for clues about the meross protocol) and it looks like the right message for the job. 

I see the firmware on the msg100 is relatively fresh but maybe there's a new update available which would 'fix' this missed namespace? I see there should be another way since the Meross app is definitely able to manage the door open/close duration for your garagedoor but still...at this point we would really need someone to MITM the protocol in order to see where this info is exchanged..

**Comment by TheOneOgre** [comment] 2023-02-20 20:28
Can conform the latest version adds the proper config for the duration sensors and upon adjusting those values, the response is exactly as expected. Thanks! @krahabb

**Comment by cor73x** [comment] 2023-02-23 23:23
@krahabb my two MSG100 are not reporting "opening" when using remote and automations based on that trigger are not working. This is also not visible in history. 
But if I open gate from HA it is correctly reported and automations are triggered, this is related to this or other problem and I should open separate issue for that?

**Comment by krahabb** [comment] 2023-02-24 07:47
Hello @cor73x,
When the open/close command is issued by the app or any external mean HA has no way to immediately update its state so it might happen that the 'signal' for the opened garage arrives at HA when its already opened (in full) and that's why I've decided to skip signaling the opening/closing transition in HA for this usage. Previously there was a logic trying to show you the transition but it was not very deterministic and I've decided to completely remove that in favor of a more 'controllable' behavior
It could be different if the device is paired on your provate MQTT but in this case I would need a trace/log documenting the traffic when you issue your open and close command from the app, but of course, if you're using the app you're not using your private broker!

**Comment by cor73x** [comment] 2023-02-26 10:35
@krahabb Thank you for response :) 
I'm not using private MQTT (at least yet), my MSG100's are connected to HomeKit, Meross app and HA instance via your integration.

In most cases, I'm opening garage door using button (radio button) which sends signal to garage door motor, which opens door. 
In this case I always receive notification from HomeKit and Meross app after 2/3 seconds after garage door starts opening. 

Based on what you said, only option to have "opening/closing" trigger working is to use private MQTT. I see probably second option: pairing this as HK accessory with HA (as based on my case, HK is receiving this notification with only slight delay, same time as Meross app).

**Comment by krahabb** [comment] 2023-02-27 10:05
Hello @cor73x,
yes, more or less...
I'm actually working on integrating the meross cloud mqtt servers into meross_lan so to have 'instant' updates of devices.
This way, you'll have the same benefits (instant push notifications) of the meross_lan private broker solution without the need to unpair your devices from the Meross Cloud.
It will take some time tho since the upgrade is really huge and I'd need to go through extensive testing but it's on the way :)

**Closed** 2024-01-13 12:12 UTC
Labels: bug, enhancement, fixed
