### ISSUE TITLE
MS100 (old version)

### ISSUE THREAD

**Issue by CTJohnK** [krahabb/meross_lan#395] opened 2024-02-26 16:05 UTC
I updated from 2.x to 4.5x over the weekend and noticed the old MS100 Temp/Humidity sensors stopped reporting the battery level.

This morning I noticed, version 5.0 is available, so I installed that version.  Unfortunately after rebooting HA, all those sensors showed "Unavailable".

The HA Logs show:
"**This error originated from a custom integration.

Logger: custom_components.meross_lan.msh300_###############################0
Source: custom_components/meross_lan/helpers/__init__.py:246
Integration: Meross LAN (documentation, issues)
First occurred: 10:49:11 AM (27 occurrences)
Last logged: 10:55:15 AM

Protocol error: namespace:Appliance.Hub.Sensor.All payload:{'error': {'code': 5001, 'detail': 'sign error'}}
Protocol error: namespace:Appliance.Hub.Sensor.Adjust payload:{'error': {'code': 5001, 'detail': 'sign error'}}
Protocol error: namespace:Appliance.Hub.Battery payload:{'error': {'code': 5001, 'detail': 'sign error'}}
Appliance.Control.Multiple failed with no response: requests=4 expected size=4917
Appliance.Control.Multiple failed with no response: requests=4 expected size=3347**"

Next, I pulled up the Meross Hub and re-configured it to add a Device Key.  A minute later the sensors became available, but the battery level is still showing 'Unavailable'.

Is this expected behavior with the newer versions of the integration?

**Comment by krahabb** [comment] 2024-02-26 17:00
Not really...I'll see what could be wrong.
As for the device key you were still likely using an old feature allowing to communicate without a proper device key so that's expected.
The battery level missing is instead an issue though

**Comment by CTJohnK** [comment] 2024-02-27 01:49
Agree about the key, I was just relaying the steps.

Please let me know if you need anything, the batteries are only a couple of weeks old, so there's time before they're needing to be replaced.

**Comment by CTJohnK** [comment] 2024-02-27 12:11
I opened HA this morning to check the temperature of our plants and the battery level is appearing for all the devices.  They were not when I looked last night.

**Comment by krahabb** [comment] 2024-02-27 14:16
Yes..I was (hopefully) expecting this.
It might be the battery queries are 'lost' from time to time (I have to check when and why) and, since they're on a long timeout, you might see them unavailable when the device comes online. I think the new 'multiple packed messages' feature could be prone to this kind of polling message loss. There are some checks though but it cleraly needs some more tuning.

Thank you for your patience

**Comment by krahabb** [comment] 2024-03-22 14:55
Closing this down since I cannot get to reproduce the issue. It looks like the actual implementation is stable enough to consistently query the battery

**Closed by krahabb** 2024-03-22 14:55 UTC
Labels: bug
