### ISSUE TITLE
Mss425f 

### ISSUE THREAD

**Issue by drako86** [krahabb/meross_lan#33] opened 2021-07-05 07:44 UTC
Hi, I'm writing to you because the multicry in question, even though it works perfectly in the lanes, does not perform asynchronous synchronisation, in the sense that it does not update the states of the various exits until I refute integration. If the reloading, on the other hand, correctly updates the state. I must say that I use the HTTP mode and with a request of 30

**Comment by krahabb** [comment] 2021-07-05 16:43
Hello @drako86,
by using HTTP you're not getting immediate status update but, with a 30 sec polling period you should get a correct state in at last 30 sec indeed.
Reloading the integration shouldnt be needed. Of course if you switch on and off in less than 30 sec you'll loose the transition and only get the state every 30 sec.
If waiting (those 30 sec) doesnt work I'll further investigate the issue but I'd need the trace from your device in order to see what's happening. I'll instruct you in case

**Comment by drako86** [comment] 2021-07-05 18:07
Hi, and thank you, I have other devices linked to already supplements,
2 msl430 
1 mss310 
all function well (logical with 30 seconds delay) but this, no, not even if I wait hours 
(I need to charge integration to update the state)

So tell me what you need, and I'll tell you

Thanks a lot

**Comment by krahabb** [comment] 2021-07-05 19:43
Hey @drako86 ,
thank you for pointing out.
I'll go to the point: from the integration configuration UI, open the configuration of the 'mss425' and check the 'Activate debug trace...'. After this, a very detailed message tracing will be saved under 'custom_components/meross_lan/traces' for your device. It's a CSV file that will be 'finished' in 10 minutes automatically .
During this time turn on/off the ports the way you usually do and when finished send me the trace (simply post it here)
I'll check it asap

Thank you!

**Comment by drako86** [comment] 2021-07-05 20:23
Thanks a lot

[mss425f-2007164290493090820048e1e9258467.csv](https://github.com/krahabb/meross_lan/files/6766122/mss425f-2007164290493090820048e1e9258467.csv)

Here you go

**Comment by krahabb** [comment] 2021-07-06 16:02
Hello @drako86 
Thank you for your quick post. I've already worked it out and (guess) I've fixed the code to correctly poll the mss425f.
The problem is I had to remaster a bit the code behaviour in order to try to make it 'future' proof since I really struggle to find a 'general' rule on how the different devices behave (probably no rule?)

Anyway I expect to release the update tonight after some more testing in order to not break any existing installation

**Comment by drako86** [comment] 2021-07-06 16:58
Excellent! You're a great ! Don't rush, you do things with the best chance of !! No one dies! Ps: If I can send you anything to help you in your work, don't hesitate!

**Comment by drako86** [comment] 2021-07-07 19:49
Hi! I've done The update, it seems it's all going, ^, thank you infinitely

**Comment by krahabb** [comment] 2021-07-08 07:03
Thank you!
closing this

**Closed by krahabb** 2021-07-08 07:03 UTC
