### ISSUE TITLE
MerossDevice(Smart Switch (*****************e9bb0527)): MLUpdate(update.******_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process

### ISSUE THREAD

**Issue by lboue** [krahabb/meross_lan#378] opened 2024-01-23 17:28 UTC
The interface Home assistant prompts me to start the device update. This generates an exception in the logs and doesn't work.

![image](https://github.com/krahabb/meross_lan/assets/938089/746b296e-37ac-4643-939a-93db2215da3b)

Smart Plug entree 2302 Update_firmware

- Installed version 	9.3.26
- Latest version 		9.5.35

Added support for the standby killer feature.
Fixed a power consumption issue.
Fixed an issue where the device may unbind itself.
Improved the device's online stability.

## Version of the custom_component

- Meross LAN v4.5.3

## Configuration

```yaml

This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:166
Integration: Meross LAN (documentation, issues)
First occurred: 11:45:53 AM (6 occurrences)
Last logged: 6:24:33 PM

MerossCloudProfile(2927516): Meross cloud api reported new devices but MQTT publishing is disabled: skipping automatic discovery
MerossMQTTConnection(2927516:mqtt-eu.meross.com:443): MQTT publishing is not allowed for this profile (device_id=2302200197404551080b48e1e9bb03bd)
MerossDevice(Smart Switch (2302208952499451080b48e1e9bb0527)): MLUpdate(update.smart_plug_entree_2302_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
MerossDevice(Smart Switch (2302200197404551080b48e1e9bb03bd)): MLUpdate(update.smart_plug_bureau_ludo_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process

```

## Describe the bug
The interface Home assistant prompts me to start the device update. This generates an exception in the logs and doesn't work.
Device Type: Smart Switch (mss315)

## Debug log

```text

This error originated from a custom integration.

Logger: custom_components.meross_lan
Source: custom_components/meross_lan/helpers.py:166
Integration: Meross LAN (documentation, issues)
First occurred: 11:45:53 AM (6 occurrences)
Last logged: 6:24:33 PM

MerossCloudProfile(2927516): Meross cloud api reported new devices but MQTT publishing is disabled: skipping automatic discovery
MerossMQTTConnection(2927516:mqtt-eu.meross.com:443): MQTT publishing is not allowed for this profile (device_id=2302200197404551080b48e1e9bb03bd)
MerossDevice(Smart Switch (2302208952499451080b48e1e9bb0527)): MLUpdate(update.smart_plug_entree_2302_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
MerossDevice(Smart Switch (2302200197404551080b48e1e9bb03bd)): MLUpdate(update.smart_plug_bureau_ludo_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
```

```
2024-01-23 18:14:48.993 ERROR (MainThread) [meross_iot.manager] Timeout occurred while waiting a response for message b'{"header":{"from":"/app/2927516-bdc0c98c5f2a628a69ce6f5ccdd642f1/subscribe","messageId":"fe56cead874ac4f182167eba7b8bfc6a","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"aff8305c998f57865731014b74edff29","timestamp":1706030079,"triggerSrc":"Android","uuid":"2302200197404551080b48e1e9bb03bd"},"payload":{"channel":0}}' sent to device uuid 2302200197404551080b48e1e9bb03bd. Timeout was: 10.000000 seconds. Mqtt Host: mqtt-eu.meross.com:443.
2024-01-23 18:14:48.993 ERROR (MainThread) [custom_components.meross_cloud.sensor] Error occurred.
-------------------------------------
Component version: 0.4.6.0rc2
Device info: 
	Name: Smart Plug bureau Ludo
	UUID: 2302200197404551080b48e1e9bb03bd
	Type: mss315
	HW Version: 9.0.0
	FW Version: 9.3.26
Error Message: "An exception occurred"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 500, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 903, in _async_send_and_wait_ack
    return await asyncio.wait_for(future, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 502, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/meross_cloud/sensor.py", line 151, in async_update
    await self._device.async_get_instant_metrics(channel=self._channel_id)
  File "/usr/local/lib/python3.11/site-packages/meross_iot/controller/mixins/electricity.py", line 41, in async_get_instant_metrics
    result = await self._execute_command(method="GET",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/controller/device.py", line 308, in _execute_command
    return await self._manager.async_execute_cmd(destination_device_uuid=self.uuid,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 847, in async_execute_cmd
    return await self.async_execute_cmd_client(client=client,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 884, in async_execute_cmd_client
    response = await self._async_send_and_wait_ack(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/meross_iot/manager.py", line 910, in _async_send_and_wait_ack
    raise CommandTimeoutError(message=str(message), target_device_uuid=target_device_uuid, timeout=timeout)
meross_iot.model.exception.CommandTimeoutError
2024-01-23 18:16:15.974 WARNING (MainThread) [meross_iot.manager] Received a push notification (Namespace.SYSTEM_ONLINE, raw_data: {"online": {"status": 1}}) for device(s) (2302208952499451080b48e1e9bb0527) that are not available in the local registry. Trigger a discovery to intercept those events.
2024-01-23 18:16:15.974 WARNING (MainThread) [meross_iot.manager] Received a push notification for a device that is not available in the local registry. You may need to trigger a discovery to catch those updates. Device-UUID: 2302208952499451080b48e1e9bb0527
2024-01-23 18:16:15.974 WARNING (MainThread) [meross_iot.manager] Uncaught push notification Namespace.SYSTEM_ONLINE. Raw data: {"online": {"status": 1}}
2024-01-23 18:17:54.952 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Smart Switch (2302208952499451080b48e1e9bb0527)): MLUpdate(update.smart_plug_entree_2302_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
2024-01-23 18:18:12.313 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Smart Switch (2302200197404551080b48e1e9bb03bd)): MLUpdate(update.smart_plug_bureau_ludo_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
2024-01-23 18:24:24.008 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Smart Switch (2302200197404551080b48e1e9bb03bd)): MLUpdate(update.smart_plug_bureau_ludo_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
2024-01-23 18:24:33.622 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(Smart Switch (2302208952499451080b48e1e9bb0527)): MLUpdate(update.smart_plug_entree_2302_update_firmware): The firmware update feature is not (yet) available: use the Meross app to carry the process
```

[home-assistant_meross_lan_2024-01-23T17-32-42.510Z.log](https://github.com/krahabb/meross_lan/files/14027900/home-assistant_meross_lan_2024-01-23T17-32-42.510Z.log)

**Comment by ngensys** [comment] 2024-01-24 09:39
May Meross stopped this firmware 9.5.35, because it causes a lot of problems.
I updated all my MSS315 with the App and cant use them anymore. Always timeout, even with the Meross-App.
Look in the Forum within the App to find more about the problem.

**Comment by krahabb** [comment] 2024-01-24 10:26
Duplicate of #363.

The meross_lan firmware update feature is 'as is' so the fact that the update process doesn't work is by design.
I agree this might be confusing (repair and then warning...) since the idea was to bring it to fully working but at the moment, it still isn't and I have no devices to test/experiment on that.

**Closed by krahabb** 2024-01-24 10:26 UTC
